### ISSUE TITLE
cityscapesScripts version

### ISSUE THREAD

**Issue by jamesbc123** [CAPTAIN-WHU/iSAID_Devkit#32]
Which version of cityscapesScripts is used? It is not written in the yml file.

**Comment by ucasyjz** [comment]
i meet the error 
Traceback (most recent call last):
  File "preprocess.py", line 165, in <module>
    convert_cityscapes_instance_only(args.datadir, args.outdir)
  File "preprocess.py", line 120, in convert_cityscapes_instance_only
    objects = cs.instances2dict_with_polygons([seg_fullname],[inst_fullname], verbose=True)
  File "/mnt/AIService/FoundationModel/zzn/yjz/data/iSAID_Devkit-master/preprocess/cityscapesScripts/cityscapesscripts/evaluation/instances2dict_with_polygons.py", line 76, in instances2dict_with_polygons
    instanceObj = Instance(imgNp,imgNp_seg, instanceId)
TypeError: __init__() takes 3 positional arguments but 4 were given
