### ISSUE TITLE
Key Error when running preprocess.py 

### ISSUE THREAD

**Issue by ikarakaya89** [CAPTAIN-WHU/iSAID_Devkit#7]
After split.py,  strating preprocess.py does not work. 
Error:

Traceback (most recent call last):
  File "preprocess.py", line 158, in <module>
    convert_cityscapes_instance_only(args.datadir, args.outdir)
  File "preprocess.py", line 111, in convert_cityscapes_instance_only
    objects = cs.instances2dict_with_polygons([seg_fullname],[inst_fullname], verbose=True)
  File "/mnt/blockstorage/ikarakaya/Mask_RCNN/isaid_devkit/preprocess/cityscapesScripts/cityscapesscripts/evaluation/instances2dict_with_polygons.py", line 88, in instances2dict_with_polygons
    print(m2label[instanceObj.labelID])
KeyError: 127

**Comment by akshitac8** [comment]
Hi, @ikarakaya89 Can you let me know the directory structure for the dataset you created on your machine?

**Comment by akshitac8** [comment]
@ikarakaya89 Is the issue solved?

**Comment by ikarakaya89** [comment]
Yes, Thanks. The reason for the mistake is to use cv2.imread instead of  lycan.

**Comment by akshitac8** [comment]
Thank you @ikarakaya89
